# Generated by Django 2.2.4 on 2020-04-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='group_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='short_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
