# Generated by Django 2.2.4 on 2020-05-01 23:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200501_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Social'), (2, 'Talk'), (3, 'Workshop'), (4, 'Others')], default='', max_length=7),
        ),
    ]
