# Generated by Django 2.2.4 on 2020-05-07 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('services', '0008_auto_20200507_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='listing',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='associated_user', to='users.User'),
        ),
    ]
