# Generated by Django 2.2.4 on 2020-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20200507_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reccomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=None)),
                ('reccomended_items', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
