# Generated by Django 2.2.4 on 2020-05-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_reccomendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reccomendation',
            new_name='Recommendation',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='reccomended_items',
            new_name='recommended_items',
        ),
    ]
