# Generated by Django 2.2.4 on 2020-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20200508_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
