# Generated by Django 2.2.4 on 2020-04-29 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='default_password', max_length=1024)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.BigIntegerField(default=0)),
                ('rating', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_val', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='users.User')),
            ],
        ),
    ]
